"use client";
import { useEffect, useState } from "react";
// WELLNESS_GOOGLE_FIT_ADMIN_DEEP_PROBE_UI_V126M58_2
function c(v:any){return String(v??"").trim()} function n(v:any){const x=Number(v);return Number.isFinite(x)?x:0}
const names:any={"com.google.step_count.delta":"Steps","com.google.distance.delta":"Distance","com.google.calories.expended":"Calories","com.google.active_minutes":"Active Minutes"};
export default function Page(){
 const [id,setId]=useState(""),[date,setDate]=useState("2026-08-06"),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const p=new URLSearchParams(location.search);const i=p.get("participant_id")||"";const d=p.get("date")||"2026-08-06";setId(i);setDate(d);if(i)run(i,d)},[]);
 async function run(i=id,d=date){if(!c(i))return;setLoading(true);setError("");setData(null);const r=await fetch(`/api/wellness/admin/google-fit-raw-diagnostic/deep-probe?participant_id=${encodeURIComponent(i)}&date=${encodeURIComponent(d)}&_=${Date.now()}`,{credentials:"include",cache:"no-store"}).then(async x=>({...await x.json().catch(()=>({})),http_status:x.status})).catch(e=>({ok:false,message:e?.message||"Network error"}));if(r.ok)setData(r);else setError(r.message||"Probe gagal");setLoading(false)}
 const tone=data?.verdict==="API_HTTP_OK_EMPTY_DATA"?"border-amber-200 bg-amber-50 text-amber-900":data?.verdict==="GOOGLE_DATA_VISIBLE_BUT_DB_EMPTY"?"border-rose-200 bg-rose-50 text-rose-900":"border-sky-200 bg-sky-50 text-sky-900";
 return <main className="min-h-screen bg-slate-50 p-4 md:p-8 text-slate-950"><div className="mx-auto max-w-7xl space-y-5">
  <section className="rounded-[2rem] border border-slate-200 bg-white p-5 md:p-7"><div className="text-[10px] font-black uppercase tracking-[.16em] text-amber-600">Google Fit Admin Deep Probe</div><h1 className="mt-1 text-2xl font-black">Cek Kenapa Data Tidak Ketarik</h1><p className="mt-2 text-sm font-semibold text-slate-500">READ ONLY · exact date · tidak menjalankan sync dan tidak menulis database.</p><div className="mt-5 grid gap-3 md:grid-cols-[1fr_220px_180px]"><input value={id} onChange={e=>setId(e.target.value)} placeholder="Participant ID" className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 font-bold"/><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-2xl border border-slate-200 px-4 py-3 font-bold"/><button onClick={()=>run()} disabled={loading||!c(id)} className="rounded-2xl bg-slate-950 px-4 py-3 font-black text-white disabled:opacity-40">{loading?"Probing...":"Probe Google"}</button></div>{error?<div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 p-4 font-bold text-rose-800">{error}</div>:null}</section>
  {data?<><section className={`rounded-[2rem] border p-5 ${tone}`}><div className="text-xs font-black uppercase">Verdict Admin</div><div className="mt-1 text-xl font-black">{data.verdict}</div><div className="mt-2 text-xs font-bold">{data.date} · UTC {data.utc_window?.start} → {data.utc_window?.end}</div></section>
  <section className="grid gap-4 md:grid-cols-3"><Card t="Peserta"><b>{data.participant?.name}</b><br/>Kode {data.participant?.code} · ID {data.participant?.id}</Card><Card t="OAuth"><b>{data.oauth?.email||"-"}</b><br/>Scope: {data.oauth?.scope||"-"}<br/>userinfo HTTP {data.oauth?.userinfo_http} · tokeninfo HTTP {data.oauth?.tokeninfo_http}</Card><Card t="Signal"><b>Google calls OK: {String(data.signals?.all_google_calls_http_ok)}</b><br/>Aggregate points: {data.signals?.aggregate_point_count}<br/>Sources: {data.signals?.all_source_count} · Sessions: {data.signals?.session_count} · DB rows: {data.signals?.db_row_count}</Card></section>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Exact Day Google API Probe</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr className="border-b"><Th>Metric</Th><Th>Period HTTP</Th><Th>Period bucket/point</Th><Th>Period total</Th><Th>24h HTTP</Th><Th>24h bucket/point</Th><Th>24h total</Th><Th>Sources</Th></tr></thead><tbody>{Object.entries(data.google?.per_type||{}).map(([k,v]:any)=><tr key={k} className="border-b border-slate-100"><Td>{names[k]||k}</Td><Td>{v.period?.http_status}{v.period?.error?` · ${v.period.error}`:""}</Td><Td>{v.period?.bucket_count}/{v.period?.point_count}</Td><Td>{v.period?.total}</Td><Td>{v.duration?.http_status}{v.duration?.error?` · ${v.duration.error}`:""}</Td><Td>{v.duration?.bucket_count}/{v.duration?.point_count}</Td><Td>{v.duration?.total}</Td><Td>{v.sources?.http_status} · {v.sources?.count}</Td></tr>)}</tbody></table></div></section>
  <section className="grid gap-4 lg:grid-cols-2"><Card t="All Data Sources"><b>HTTP {data.google?.all_sources?.http_status} · {data.google?.all_sources?.count||0} source</b><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-[10px]">{JSON.stringify(data.google?.all_sources?.samples||[],null,2)}</pre></Card><Card t="Sessions"><b>HTTP {data.google?.sessions?.http_status} · {data.google?.sessions?.count||0} session</b><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-[10px]">{JSON.stringify(data.google?.sessions?.samples||[],null,2)}</pre></Card></section>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-5"><h2 className="font-black">DB Google Fit tanggal ini ({data.db_rows?.length||0})</h2><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-[10px]">{JSON.stringify(data.db_rows||[],null,2)}</pre></section></>:null}
 </div></main>
}
function Card({t,children}:{t:string,children:any}){return <section className="rounded-[2rem] border border-slate-200 bg-white p-5 text-sm leading-6"><div className="mb-2 text-xs font-black uppercase text-slate-500">{t}</div>{children}</section>}function Th({children}:{children:any}){return <th className="px-3 py-3 font-black">{children}</th>}function Td({children}:{children:any}){return <td className="px-3 py-3 font-bold align-top">{children}</td>}
