// WELLNESS_COACH_MEMBER_MONITORING_V126M55
import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/server/supabaseAdmin";
import { buildCoachGroupUnitMap, canCoachAccessParticipant, dedupeCoachParticipants } from "@/lib/wellness/coachGroupAccess";
import { loadWellnessMemberMonitoring } from "@/lib/wellness/memberMonitoringServer";
export const dynamic="force-dynamic"; export const runtime="nodejs"; export const maxDuration=60;
function clean(v:any){return String(v??"").trim()}
function active(v:any){return ![false,0,"0","false","inactive","nonaktif"].includes(typeof v==="string"?v.toLowerCase():v)}
async function getCoach(req:NextRequest,s:any){const token=req.cookies.get("wellness_coach_session")?.value||"";if(!token)return null;const r=await s.from("wellness_coach_auth_sessions").select("*, coach:wellness_coach_users(*)").eq("session_token",token).gt("expires_at",new Date().toISOString()).maybeSingle();return r.error||!r.data?.coach||r.data.coach.is_active===false?null:r.data.coach}
export async function GET(req:NextRequest){try{const s=getSupabaseAdmin(),coach=await getCoach(req,s);if(!coach)return NextResponse.json({ok:false,message:"Session coach belum aktif."},{status:401});const [ar,gr,pr,cr]=await Promise.all([s.from("wellness_coach_group_assignments").select("*").eq("coach_user_id",coach.id).eq("is_active",true).order("id",{ascending:true}),s.from("wellness_group_units").select("*").limit(5000),s.from("wellness_participants").select("*").limit(10000),s.from("wellness_companies").select("id,name").limit(2000)]);if(ar.error)throw ar.error;if(gr.error)throw gr.error;if(pr.error)throw pr.error;const map=buildCoachGroupUnitMap(gr.data||[]);const participants=dedupeCoachParticipants(pr.data||[]).filter((r:any)=>active(r?.is_active)).filter((r:any)=>canCoachAccessParticipant(r,ar.data||[],map));const companies=new Map<number,string>((cr.data||[]).map((r:any)=>[Number(r.id),clean(r.name)]));const monitoring=await loadWellnessMemberMonitoring({supabase:s,participants,groupUnitMap:map,companyNameById:companies});return NextResponse.json({ok:true,coach:{id:coach.id,name:clean(coach.name||coach.full_name||coach.username||"Coach")},groups:(ar.data||[]).map((a:any)=>{const id=clean(a?.wellness_group_unit_id);return{id,name:clean(map.get(id)?.name||a?.group_name||"Group")}}),...monitoring},{headers:{"Cache-Control":"no-store, max-age=0"}})}catch(e:any){return NextResponse.json({ok:false,message:e?.message||"Gagal memuat monitoring Coach."},{status:500})}}
