import { NextRequest, NextResponse } from "next/server";
import { getSessionUser } from "@/lib/server/session";
import { getSupabaseAdmin } from "@/lib/server/supabaseAdmin";
export const dynamic = "force-dynamic";
function fail(message:string,status=400,extra:Record<string,unknown>={}){return NextResponse.json({ok:false,message,...extra},{status});}
function clean(v:unknown){const s=String(v??"").trim();return !s||["null","undefined","nan","-","—"].includes(s.toLowerCase())?"":s;}
function isObj(v:any){return v&&typeof v==="object"&&!Array.isArray(v);}
function applyMapping(rowData:Record<string,any>,mapping:Record<string,any>){const out={...(rowData||{})}; if(!isObj(mapping)) return out; for(const [target,source] of Object.entries(mapping)){const t=clean(target),s=clean(source); if(t&&s in rowData&&clean(rowData[s])) out[t]=rowData[s];} return out;}
function firstMapping(rows:any[]){for(const row of rows||[]){if(isObj(row.field_mapping)&&Object.keys(row.field_mapping).length) return row.field_mapping; if(isObj(row.row_data?._AI_MCU_FIELD_MAPPING)) return row.row_data._AI_MCU_FIELD_MAPPING;} return {};}
export async function POST(req:NextRequest){try{const user=getSessionUser(req); if(!user) return fail("Unauthorized",401); const body=await req.json().catch(()=>({})); const sourceId=Number(body.sourceId||body.source_id||0); const targetKey=clean(body.targetKey)||"KATEGORI"; const modelName=clean(body.modelName)||"fit_status"; const minRows=Number(body.minRows||20); if(!sourceId) return fail("sourceId wajib dipilih."); const engineUrl=clean(process.env.AI_MCU_ENGINE_URL); if(!engineUrl) return fail("AI_MCU_ENGINE_URL belum diset di Vercel."); const supabase=getSupabaseAdmin(); const rr=await supabase.from("ai_mcu_import_rows").select("id,source_id,participant_id,dataset_role,row_data,field_mapping,participant_name,mcu_id,nik").eq("source_id",sourceId).order("id",{ascending:true}); if(rr.error) return fail(rr.error.message,500); const rows=rr.data||[]; const globalMapping=firstMapping(rows); const prepared=rows.map((row:any)=>{const m=isObj(row.field_mapping)&&Object.keys(row.field_mapping).length?row.field_mapping:globalMapping; const flat=applyMapping(row.row_data||{},m); flat.NAMA=clean(flat.NAMA)||clean(flat.Nama)||clean(row.participant_name); flat.MCU_ID=clean(flat.MCU_ID)||clean(flat.NOMCU)||clean(flat["NO MCU"])||clean(row.mcu_id)||String(row.id); flat.NIK=clean(flat.NIK)||clean(row.nik); flat._field_mapping=m; flat._import_row_id=row.id; flat._dataset_role=row.dataset_role; return flat;}); const labeled=prepared.filter((r:any)=>clean(r[targetKey])); if(labeled.length<minRows) return fail(`Data berlabel ${targetKey} belum cukup. Tersedia ${labeled.length}, minimal ${minRows}.`,400,{sourceId,targetKey,totalRows:rows.length,labeledRows:labeled.length}); const er=await fetch(`${engineUrl.replace(/\/$/,"")}/train-ai-mcu-ml`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows:labeled,targetKey,modelName,minRows})}); const ej=await er.json().catch(()=>({ok:false,message:"Response Python engine bukan JSON."})); if(!er.ok||!ej.ok) return fail(ej.message||"Training ML gagal di Python engine.",500,{engineStatus:er.status,engineResponse:ej}); return NextResponse.json({ok:true,message:"Training ML berhasil.",sourceId,totalRows:rows.length,labeledRows:labeled.length,engine:ej});}catch(e:any){return fail(e?.message||"Training ML gagal.",500);}}
