-- =========================================================
-- CAPASKA scoring options config v40
-- Jalankan setelah sql/capaska_all_reference_parameters_v11.sql atau setelah Seed / Refresh Default CAPASKA.
-- Tidak menghapus peserta/hasil. Hanya memperkaya config_json parameter CAPASKA dengan opsi, skor, dan critical flag.
-- =========================================================

BEGIN;

WITH scoring_config(parameter_name, config_json) AS (
  VALUES
  ('Lensakontak/ kaca mata', '{"options": [{"label": "Tidak menggunakan", "value": "Tidak menggunakan", "score": 3, "is_critical": false, "note": ""}, {"label": "Menggunakan", "value": "Menggunakan", "score": -1, "is_critical": false, "note": ""}], "max_score": 3, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Tes buta warna', '{"options": [{"label": "Tidak buta warna", "value": "Tidak buta warna", "score": 3, "is_critical": false, "note": ""}, {"label": "Buta warna parsial", "value": "Buta warna parsial", "score": -10, "is_critical": true, "note": ""}, {"label": "Buta warna total", "value": "Buta warna total", "score": -10, "is_critical": true, "note": ""}], "max_score": 3, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Strabismus / Juling', '{"options": [{"label": "(-) / (-)", "value": "(-) / (-)", "score": 3, "is_critical": false, "note": ""}, {"label": "(+) / (-)", "value": "(+) / (-)", "score": -5, "is_critical": false, "note": ""}, {"label": "(-) / (+)", "value": "(-) / (+)", "score": -5, "is_critical": false, "note": ""}, {"label": "(+) / (+)", "value": "(+) / (+)", "score": -5, "is_critical": false, "note": ""}], "max_score": 3, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Pemeriksaan Visus OD  / OS', '{"options": [{"label": "Normal 6/6", "value": "Normal 6/6", "score": 3, "is_critical": false, "note": ""}, {"label": "<6/6 - 6/12", "value": "<6/6 - 6/12", "score": 2, "is_critical": false, "note": ""}, {"label": "<6/12", "value": "<6/12", "score": -10, "is_critical": true, "note": ""}], "max_score": 3, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Karang Gigi', '{"options": [{"label": "Negative", "value": "Negative", "score": 2, "is_critical": false, "note": ""}, {"label": "Positive", "value": "Positive", "score": -1, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Caries Dentis', '{"options": [{"label": "0 caries", "value": "0 caries", "score": 3, "is_critical": false, "note": ""}, {"label": "1 caries", "value": "1 caries", "score": -1, "is_critical": false, "note": ""}, {"label": "2 caries", "value": "2 caries", "score": -2, "is_critical": false, "note": ""}, {"label": "3 caries", "value": "3 caries", "score": -3, "is_critical": false, "note": ""}, {"label": ">3 caries", "value": ">3 caries", "score": -10, "is_critical": true, "note": ""}], "max_score": 3, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Tumpatan Gigi', '{"options": [{"label": "0 tumpatan", "value": "0 tumpatan", "score": 2, "is_critical": false, "note": ""}, {"label": "<=5 tumpatan", "value": "<=5 tumpatan", "score": 1, "is_critical": false, "note": ""}, {"label": ">5 tumpatan", "value": ">5 tumpatan", "score": -5, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Impaksi gigi', '{"options": [{"label": "0 gigi", "value": "0 gigi", "score": 3, "is_critical": false, "note": ""}, {"label": "1 gigi", "value": "1 gigi", "score": 2, "is_critical": false, "note": ""}, {"label": "2 gigi impaksi / impaksi 1 gigi depan", "value": "2 gigi impaksi / impaksi 1 gigi depan", "score": 1, "is_critical": false, "note": ""}, {"label": ">2 gigi impaksi atau 2 gigi depan impaksi", "value": ">2 gigi impaksi atau 2 gigi depan impaksi", "score": -5, "is_critical": false, "note": ""}, {"label": "≥4 gigi", "value": "≥4 gigi", "score": -10, "is_critical": true, "note": ""}], "max_score": 3, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Kehilangan Gigi (Baik depan maupun belakang)', '{"options": [{"label": "0 gigi", "value": "0 gigi", "score": 2, "is_critical": false, "note": ""}, {"label": "1 gigi", "value": "1 gigi", "score": 1, "is_critical": false, "note": ""}, {"label": "2 gigi", "value": "2 gigi", "score": 0, "is_critical": false, "note": ""}, {"label": ">2 gigi", "value": ">2 gigi", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Infeksi Gusi', '{"options": [{"label": "Negative", "value": "Negative", "score": 1, "is_critical": false, "note": ""}, {"label": "Positive", "value": "Positive", "score": -1, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Dental panoramic', '{"options": [{"label": "Normal", "value": "Normal", "score": 3, "is_critical": false, "note": ""}, {"label": "ditemukan kelainan", "value": "ditemukan kelainan", "score": -1, "is_critical": false, "note": ""}], "max_score": 3, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Membran timpani', '{"options": [{"label": "Intak", "value": "Intak", "score": 2, "is_critical": false, "note": ""}, {"label": "Tidak Intak", "value": "Tidak Intak", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Serumen', '{"options": [{"label": "Tidak ada", "value": "Tidak ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ada serumen", "value": "Ada serumen", "score": 1, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Tonsil', '{"options": [{"label": "T0 - T1", "value": "T0 - T1", "score": 2, "is_critical": false, "note": ""}, {"label": "Sudah tonsilektomi", "value": "Sudah tonsilektomi", "score": 2, "is_critical": false, "note": ""}, {"label": "T2a-T2a", "value": "T2a-T2a", "score": 1, "is_critical": false, "note": ""}, {"label": "T2b-T2b", "value": "T2b-T2b", "score": -1, "is_critical": false, "note": ""}, {"label": "T3-T3", "value": "T3-T3", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Rhinitis Alergi (divide)', '{"options": [{"label": "Negative", "value": "Negative", "score": 2, "is_critical": false, "note": ""}, {"label": "Positive", "value": "Positive", "score": 1, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Epistaksis 1 tahun terakhir', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -1, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Tes Garputala (Weber) 512 Hz', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Berat Badan (Kg)', '{"options": [{"label": "Sesuai juknis", "value": "Sesuai juknis", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak sesuai juknis", "value": "Tidak sesuai juknis", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('TB. (Cm)', '{"options": [{"label": "Sesuai juknis", "value": "Sesuai juknis", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak sesuai juknis", "value": "Tidak sesuai juknis", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Tanda Vital', '{"options": [{"label": "Normal", "value": "Normal", "score": 2, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": 1, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Tato kulit', '{"options": [{"label": "Tidak ada tato", "value": "Tidak ada tato", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada tato", "value": "Ada tato", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Tindik (selain anting) Wanita : hanya 1 / telinga', '{"options": [{"label": "Tidak ada", "value": "Tidak ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Wanita hanya 1 / telinga", "value": "Wanita hanya 1 / telinga", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada (pria) Wanita >1)", "value": "Ada (pria) Wanita >1)", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Pemeriksaan Fisik Jantung', '{"options": [{"label": "Normal", "value": "Normal", "score": 2, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": 1, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Pemeriksaan Fisik Paru', '{"options": [{"label": "Normal", "value": "Normal", "score": 2, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": 1, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hernia', '{"options": [{"label": "Tidak ada", "value": "Tidak ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('NT Epigastrum', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -2, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Liver', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -2, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Bising Usus', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -2, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Bekas Operasi (>6Bulan)', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -2, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Benjolan', '{"options": [{"label": "Tidak ada", "value": "Tidak ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hemoroid eksterna', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": 0, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hemoroid interna', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": 0, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Fisura ani', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": 0, "is_critical": false, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Struktur/Prolaps recti', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hidronefrosis', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Kelainan kongenital', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hipospadia', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hidrokel', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Undescensus testis', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Batu sal kemih', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Cystitis akut / kronis', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Post operasi varikokel', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Phimosis', '{"options": [{"label": "Normal", "value": "Normal", "score": 1, "is_critical": false, "note": ""}, {"label": "Tidak Normal", "value": "Tidak Normal", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Kelainan Anatomi Jantung', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Kelainan Irama Jantung', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Iskemik Miocardial', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Kelainan kongenital jantung', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Kelainan Arteri pada ekstremitas', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Varises Tungkai (insufisiensi vena)', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -1, "is_critical": false, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('sindaktili', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('polidaktili', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('spina bifida', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('mallet finger', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hiperekstensi lengan', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hammer toe', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hallux valgus', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Webbed toe', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('O/X bean', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Pes planus / kaki datar', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Polidactily', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Hiperekstensi kaki', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('General Laxity', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 1, "is_critical": false, "note": ""}, {"label": "Ada", "value": "Ada", "score": -10, "is_critical": true, "note": ""}], "max_score": 1, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Skoliosis', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ringan", "value": "Ringan", "score": -1, "is_critical": false, "note": ""}, {"label": "Sedang / Berat", "value": "Sedang / Berat", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Kifosis', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ringan", "value": "Ringan", "score": -1, "is_critical": false, "note": ""}, {"label": "Sedang / Berat", "value": "Sedang / Berat", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Lordosis', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ringan", "value": "Ringan", "score": -1, "is_critical": false, "note": ""}, {"label": "Sedang / Berat", "value": "Sedang / Berat", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Rontgen Whole Spine AP Lateral >> Skoliosis', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ringan", "value": "Ringan", "score": -1, "is_critical": false, "note": ""}, {"label": "Sedang / Berat", "value": "Sedang / Berat", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Rontgen Whole Spine AP Lateral >> Kifosis', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ringan", "value": "Ringan", "score": -1, "is_critical": false, "note": ""}, {"label": "Sedang / Berat", "value": "Sedang / Berat", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}'),
  ('Rontgen Whole Spine AP Lateral >> Lordosis', '{"options": [{"label": "Tidak Ada", "value": "Tidak Ada", "score": 2, "is_critical": false, "note": ""}, {"label": "Ringan", "value": "Ringan", "score": -1, "is_critical": false, "note": ""}, {"label": "Sedang / Berat", "value": "Sedang / Berat", "score": -10, "is_critical": true, "note": ""}], "max_score": 2, "scoring_type": "by_option", "include_in_total_score": true}')
)
UPDATE parameters p
SET config_json = scoring_config.config_json
FROM scoring_config
WHERE p.program_type = 'capaska'
  AND lower(p.name) = lower(scoring_config.parameter_name);

COMMIT;
